### ISSUE TITLE
希望有详细的writeup

### ISSUE THREAD

**Issue by potapo** [wonderkun/CTF_web#2]
谢谢，我感觉有详细的writeup更有利于大家学习

**Comment by yichinzhu** [comment]
嗯，后面会加的，那货现在正在考研，没时间弄

**Comment by wonderkun** [comment]
正在考研，到时候肯定会奉上详细的wp。

**Comment by adminlinzi** [comment]
很期待认真的writeup
加油哦 祝你考研顺利被录取。
@wonderkun

**Comment by wonderkun** [comment]
多谢   研究生已经考上了    
有些题目没写wp,过几天补上吧
