### ISSUE TITLE
请问一下400-4的问题

### ISSUE THREAD

**Issue by Crrrln** [wonderkun/CTF_web#21]
请问一下 执行语句`http://127.0.0.1:5555/index.php?file=phar://Up10aDs/y9c8v9ow3s6ans5o8oy5u3qnsdnckeva.png/1`里的1是自己构造的吗？里面的内容是什么呢？如何通过这个语句找到`F1AgIsH3r3G00d.php`呢？😭😭

**Comment by yichinzhu** [comment]
这里是利用phar文件绕过 index.php 里面强制加的.php后缀。前一步上传文件的时候上传的是一个phar打包的文件，可以简单理解为压缩包，里面包含了一个1.php文件。`include("phar://abc.phar/1.php")`就相当于include了abc.phar压缩包里面1.php。
其他细节可以参考一下这两个链接
https://blog.csdn.net/Fly_hps/article/details/86609730
https://lightless.me/archives/include-file-from-zip-or-phar.html

**Comment by Crrrln** [comment]
好的，明白了，谢谢您！非常感谢！！😆😆

**Comment by Crrrln** [comment]
您好，想再问一下，`exp.py`的文件中，语句为`fileName = fileName + randStr[i-1]`，为什么要加上i-1而不是i呢？
（在执行并调试`exp.py`文件时，res返回的好像是前一个request的回复，这是为什么呢😢）

**Comment by yichinzhu** [comment]
UNION 盲注的原理可以看这篇文章 https://wonderkun.cc/2017/02/26/%E5%9F%BA%E4%BA%8Eunion%E6%9F%A5%E8%AF%A2%E7%9A%84%E7%9B%B2%E6%B3%A8(%E6%84%9F%E8%B0%A2pcat%E7%89%9B%E4%B8%8D%E5%90%9D%E8%B5%90%E6%95%99)/ ，writeup里面的链接过期了。
简单说就是当尝试的 filename 大于真正的文件路径的时候，sql语句查询结果的第一条才是真实的文件路径。所以第`i`位的值应该是`randStr[i]`的ASCII码减一，即`int(randStr[i]) - 1`或者`randStr[i-1]`

**Comment by Crrrln** [comment]
好的，我明白了，非常感谢您的帮助！多谢！！(๑•̀ㅂ•́)و✧
