### ISSUE TITLE
web100-4的问题

### ISSUE THREAD

**Issue by daikerSec** [wonderkun/CTF_web#7]
你好，在`web100-4`的`Index.php`里面,`$KEY='ISecer:www.isecer.com';`这句话应该在`unserialize($cookie) === "$KEY"`前面吧。

**Comment by yichinzhu** [comment]
出题人的本意是在后面的，考察对PHP未定义变量行为的理解，，后面加一个`$KEY='ISecer:www.isecer.com';`只是用来迷惑人的
