### ISSUE TITLE
[New Feaure] Support for docker-compose

### ISSUE THREAD

**Issue by WangYihang** [wonderkun/CTF_web#8]
是否可以将题目的部署方式以 Docker-Compose 的形式发布呢? 这样就做题者就不必要花费太多时间在如何搭建环境上

**Comment by wonderkun** [comment]
很有打算这么做 ，我时间不是特别充足，如果你们有时间了，来帮忙搞一搞

**Comment by WangYihang** [comment]
我有时间试着整整... 到时候 Pull Request 吧, 请问是否可以把题目转载到这个仓库呢? 没有看到仓库有许可证的信息, 求授权: 
> https://github.com/SniperOJ/Challenge-Dockerfiles
